# ---------- build stage ----------
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o telegram-bot ./cmd/bot

# ---------- run stage ----------
FROM alpine:3.19

WORKDIR /app
RUN apk --no-cache add ca-certificates

COPY --from=builder /app/telegram-bot .

ENV API_BASE="http://http-service:8080"
# TELEGRAM_TOKEN зададим из docker-compose

CMD ["./telegram-bot"]
