# ---------- build stage ----------
FROM golang:1.26-alpine AS builder

WORKDIR /app

# копируем модули и тянем зависимости
COPY go.mod go.sum ./
RUN go mod download

# копируем весь исходный код
COPY . .

# собираем бинарь HTTP-сервиса
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o http-service ./cmd/http-service

# ---------- run stage: Alpine edge для yt-dlp и yt-dlp-ejs-rt-deno (YouTube/Instagram) ----------
FROM alpine:edge

WORKDIR /app
RUN apk add --no-cache ca-certificates ffmpeg yt-dlp yt-dlp-ejs-rt-deno

COPY --from=builder /app/http-service .

EXPOSE 8080

ENV DB_DSN="postgres://user:pass@postgres:5432/filemailer?sslmode=disable"

CMD ["./http-service"]
